name: JgServerWarp
version: '${project.version}'
main: com.github.sirokuri_.jgserverwarp.JgServerWarp
api-version: 1.17
authors: [ 46kuri_ ]
description: JGPlugin

commands:
  JgServerWarp:
    description: サーバー移動用関連コマンド
    permission: JgServerWarpCommand.permission.Member

permissions:
  JgServerWarpCommand.permission.Admin:
    default: op
  JgServerWarpCommand.permission.Member:
    default: true
